import { StyleSheet } from 'react-native';

export const COLORS = {
  background: '#0C0F0E',
  surface: '#151A18',
  surfaceRaised: '#1C2420',
  border: '#29322D',
  text: '#F3F7F2',
  muted: '#8C9991',
  green: '#B8F36A',
  greenDark: '#6E9839',
  orange: '#F5A65B',
  purple: '#B29CFF',
  blue: '#73B8FF',
  danger: '#FF7070',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  content: { padding: 22, paddingBottom: 48 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 26 },
  eyebrow: { color: COLORS.muted, fontSize: 11, fontWeight: '700', letterSpacing: 1.4, marginBottom: 7 },
  greeting: { color: COLORS.text, fontSize: 25, fontWeight: '700', letterSpacing: -0.5 },
  avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: COLORS.green, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: COLORS.background, fontSize: 17, fontWeight: '800' },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 30 },
  statCard: { backgroundColor: COLORS.surface, borderColor: COLORS.border, borderWidth: 1, borderRadius: 16, padding: 15, flex: 1, minHeight: 105 },
  statLabel: { color: COLORS.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1 },
  statValue: { color: COLORS.text, fontSize: 28, fontWeight: '800', marginTop: 9 },
  statUnit: { color: COLORS.muted, fontSize: 15 },
  statHint: { color: COLORS.muted, fontSize: 11, marginTop: 6 },
  flame: { color: COLORS.green, fontSize: 20 },
  progressTrack: { height: 4, borderRadius: 2, backgroundColor: COLORS.border, marginTop: 12 },
  progressFill: { height: 4, borderRadius: 2, backgroundColor: COLORS.green },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 },
  sectionTitle: { color: COLORS.text, fontSize: 20, fontWeight: '700' },
  addText: { color: COLORS.green, fontSize: 13, fontWeight: '700' },
  dayPicker: { gap: 9, paddingBottom: 23 },
  day: { width: 58, height: 72, borderRadius: 14, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center' },
  daySelected: { backgroundColor: COLORS.green, borderColor: COLORS.green },
  dayLabel: { color: COLORS.muted, fontSize: 10, fontWeight: '800', marginBottom: 8 },
  dayDate: { color: COLORS.text, fontSize: 20, fontWeight: '700' },
  daySelectedText: { color: COLORS.background },
  todayDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: COLORS.green, position: 'absolute', bottom: 6 },
  timeline: { paddingTop: 4 },
  timelineDate: { color: COLORS.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginBottom: 17 },
  taskRow: { flexDirection: 'row', minHeight: 116 },
  timeColumn: { width: 42, alignItems: 'flex-start', paddingTop: 5 },
  taskTime: { color: COLORS.text, fontSize: 12, fontWeight: '700' },
  taskEnd: { color: COLORS.muted, fontSize: 11, marginTop: 4 },
  timelineLine: { width: 20, alignItems: 'center', borderLeftWidth: 1, borderColor: COLORS.border, marginLeft: 5 },
  timelineLineLast: { borderColor: 'transparent' },
  timelineDot: { width: 9, height: 9, borderRadius: 5, marginLeft: -1, marginTop: 7, borderWidth: 2, borderColor: COLORS.background },
  taskCard: { flex: 1, backgroundColor: COLORS.surface, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, borderLeftWidth: 3, padding: 13, marginBottom: 13, marginLeft: 9 },
  taskCompleted: { opacity: 0.55 },
  taskSkipped: { opacity: 0.48 },
  taskCardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  taskTitle: { color: COLORS.text, fontSize: 15, fontWeight: '700', flex: 1 },
  taskTitleSkipped: { textDecorationLine: 'line-through', color: COLORS.muted },
  taskDescription: { color: COLORS.muted, fontSize: 12, marginTop: 6 },
  taskMeta: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  priorityPill: { fontSize: 9, fontWeight: '800', letterSpacing: 0.9 },
  duration: { color: COLORS.muted, fontSize: 10, marginLeft: 11 },
  skippedLabel: { color: COLORS.danger, fontSize: 9, fontWeight: '800', letterSpacing: 0.8, marginLeft: 'auto' },
  check: { width: 23, height: 23, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center' },
  checkDone: { backgroundColor: COLORS.green, borderColor: COLORS.green },
  checkText: { color: COLORS.background, fontWeight: '900', fontSize: 14 },
  checkDisabled: { opacity: 0.35 },
  checkProgress: { position: 'absolute', top: -4, left: -4 },
  emptyBox: { height: 62, borderWidth: 1, borderStyle: 'dashed', borderColor: COLORS.border, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9, marginLeft: 71, marginTop: 2 },
  emptyPlus: { color: COLORS.green, fontSize: 20, fontWeight: '300' },
  emptyText: { color: COLORS.muted, fontSize: 12 },
  onboarding: { flex: 1, padding: 28, justifyContent: 'center' },
  logoMark: { width: 46, height: 46, borderRadius: 15, backgroundColor: COLORS.green, alignItems: 'center', justifyContent: 'center', marginBottom: 70 },
  logoText: { color: COLORS.background, fontSize: 28, fontWeight: '900' },
  heroTitle: { color: COLORS.text, fontSize: 40, lineHeight: 45, fontWeight: '800', letterSpacing: -1.5, marginBottom: 17 },
  heroBody: { color: COLORS.muted, fontSize: 16, lineHeight: 24, maxWidth: 300, marginBottom: 34 },
  nameInput: { color: COLORS.text, fontSize: 17, borderBottomWidth: 1, borderBottomColor: COLORS.border, paddingVertical: 13, marginBottom: 28 },
  primaryButton: { height: 55, backgroundColor: COLORS.green, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', paddingHorizontal: 18, marginTop: 18 },
  primaryButtonText: { color: COLORS.background, fontWeight: '800', fontSize: 15 },
  primaryButtonArrow: { color: COLORS.background, fontSize: 19, marginLeft: 12 },
  buttonDisabled: { opacity: 0.4 },
  stepText: { color: COLORS.muted, textAlign: 'center', marginTop: 25, fontSize: 12 },
  tourCard: { flexDirection: 'row', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, padding: 17, borderRadius: 16, marginBottom: 12 },
  tourIcon: { color: COLORS.green, fontSize: 25, width: 38 },
  tourCopy: { flex: 1 },
  tourTitle: { color: COLORS.text, fontSize: 15, fontWeight: '700', marginBottom: 5 },
  tourBody: { color: COLORS.muted, fontSize: 12, lineHeight: 18 },
  detailPage: { flex: 1, backgroundColor: COLORS.background, padding: 22 },
  focusPage: { flex: 1, backgroundColor: COLORS.background, padding: 22, justifyContent: 'space-between' },
  focusCenter: { alignItems: 'center', justifyContent: 'center', flex: 1 },
  focusTitle: { color: COLORS.text, fontSize: 20, fontWeight: '700', marginBottom: 26 },
  focusCountdown: { color: COLORS.green, fontSize: 64, fontWeight: '800', letterSpacing: -2 },
  focusLabel: { color: COLORS.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginTop: 10 },
  focusEdit: { color: COLORS.muted, fontSize: 13, textAlign: 'center', paddingBottom: 14 },
  detailNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 38 },
  backText: { color: COLORS.green, fontSize: 15, fontWeight: '700' },
  closeText: { color: COLORS.muted, fontSize: 13 },
  detailAccent: { width: 42, height: 6, borderRadius: 3, marginBottom: 18 },
  detailTitle: { color: COLORS.text, fontSize: 32, fontWeight: '800', letterSpacing: -0.8 },
  detailDescription: { color: COLORS.muted, fontSize: 15, lineHeight: 22, marginTop: 10 },
  detailTime: { flexDirection: 'row', alignItems: 'center', marginTop: 30, paddingVertical: 17, borderTopWidth: 1, borderBottomWidth: 1, borderColor: COLORS.border },
  detailTimeText: { color: COLORS.text, fontSize: 24, fontWeight: '700' },
  detailArrow: { color: COLORS.muted, fontSize: 20, marginHorizontal: 14 },
  detailDuration: { color: COLORS.muted, fontSize: 12, marginLeft: 'auto' },
  countdownLabel: { color: COLORS.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.3, marginTop: 36 },
  countdown: { color: COLORS.green, fontSize: 42, fontWeight: '800', marginTop: 8, letterSpacing: -1 },
  statusText: { color: COLORS.muted, fontSize: 14, marginTop: 7 },
  detailActions: { marginTop: 'auto', paddingBottom: 18 },
  skipButton: { alignItems: 'center', marginTop: 18 },
  skipText: { color: COLORS.muted, fontSize: 13 },
  warningBox: { borderWidth: 1, borderColor: COLORS.danger, backgroundColor: '#FF707012', borderRadius: 14, padding: 16, marginTop: 25 },
  warningTitle: { color: COLORS.danger, fontWeight: '800', fontSize: 14 },
  warningCopy: { color: COLORS.text, fontSize: 13, lineHeight: 19, marginTop: 6 },
  warningActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  warningButton: { flex: 1, borderWidth: 1, borderColor: COLORS.border, borderRadius: 10, alignItems: 'center', paddingVertical: 12 },
  warningButtonDanger: { backgroundColor: COLORS.danger, borderColor: COLORS.danger },
  warningButtonText: { color: COLORS.text, fontSize: 12, fontWeight: '700' },
  warningButtonDangerText: { color: COLORS.background },
  inputLabel: { color: COLORS.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginTop: 25, marginBottom: 9 },
  formInput: { color: COLORS.text, fontSize: 17, borderWidth: 1, borderColor: COLORS.border, borderRadius: 11, padding: 13 },
  timeInputs: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  timeInput: { flex: 1 },
  timeSeparator: { color: COLORS.muted },
  priorityOptions: { flexDirection: 'row', gap: 7 },
  priorityOption: { flex: 1, paddingVertical: 11, borderRadius: 9, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center' },
  priorityOptionText: { fontSize: 11, fontWeight: '700' },
  reminderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: COLORS.border, paddingVertical: 10 },
  reminderText: { color: COLORS.text, fontSize: 13 },
  formError: { color: COLORS.danger, fontSize: 11, lineHeight: 16, marginTop: 8 },
  settingsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: COLORS.border, paddingVertical: 18, marginTop: 28 },
  settingsValue: { color: COLORS.green, fontSize: 12, fontWeight: '700' },
  resetButton: { marginTop: 35, borderWidth: 1, borderColor: COLORS.danger, borderRadius: 12, padding: 15, alignItems: 'center' },
  resetText: { color: COLORS.danger, fontSize: 13, fontWeight: '700' },
  tutorialBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: '#000000B8', zIndex: 10 },
  tutorialBubble: { position: 'absolute', backgroundColor: COLORS.surfaceRaised, borderWidth: 1, borderColor: COLORS.green, borderRadius: 16, padding: 17, width: 250 },
  tutorialPointer: { position: 'absolute', width: 12, height: 12, backgroundColor: COLORS.surfaceRaised, borderLeftWidth: 1, borderTopWidth: 1, borderColor: COLORS.green, transform: [{ rotate: '45deg' }] },
  tutorialTitle: { color: COLORS.green, fontSize: 15, fontWeight: '800', marginBottom: 6 },
  tutorialBody: { color: COLORS.text, fontSize: 13, lineHeight: 19 },
  tutorialFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15 },
  tutorialStep: { color: COLORS.muted, fontSize: 11 },
  tutorialButton: { backgroundColor: COLORS.green, borderRadius: 9, paddingHorizontal: 14, paddingVertical: 9 },
  tutorialButtonText: { color: COLORS.background, fontSize: 12, fontWeight: '800' },
  profileSheet: { backgroundColor: COLORS.surface, borderRadius: 23, padding: 25, margin: 22 },
  profileTitle: { color: COLORS.text, fontSize: 30, fontWeight: '800', marginTop: 4 },
  profileCopy: { color: COLORS.muted, fontSize: 14, lineHeight: 21, marginTop: 10 },
  historyRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 13, padding: 13, marginTop: 8 },
  historyDot: { width: 8, height: 8, borderRadius: 4, marginRight: 12 },
  historyStatus: { fontSize: 9, fontWeight: '800', letterSpacing: 0.7 },
  historyComplete: { color: COLORS.green },
  historySkipped: { color: COLORS.danger },
});
